const actions ={
    SET_PROFILE:'SET_PROFILE',
    GET_PROFILE:'GET_PROFILE',
    UPDATE_ADDRESS:'UPDATE_ADDRESS',
    GET_COUNTRY_LIST:'GET_COUNTRY_LIST',
    SET_COUNTRY_LIST:'SET_COUNTRY_LIST',
    GET_STATE_BY_COUNTRY:'GET_STATE_BY_COUNTRY',
    SET_STATE_BY_COUNTRY:'SET_STATE_BY_COUNTRY',
    GET_DISTRICTS:'GET_DISTRICTS',
    SET_DISTRICTS:'SET_DISTRICTS',
    SET_PROFILE_PICTURE:'SET_PROFILE_PICTURE',
    SET_DOCENTRY_PICTURE:'SET_DOCENTRY_PICTURE',
    GET_DOCENTRY_PICTURE:'GET_DOCENTRY_PICTURE',
    GET_ABOUT_US:"GET_ABOUT_US",
    SET_ABOUT_US:"SET_ABOUT_US",
    UPDATE_USER_DEVICE_DATA:'UPDATE_USER_DEVICE_DATA'
}
export default actions;