const actions = {
    GET_ACTIVE_SCHEMES_LIST:'GET_ACTIVE_SCHEMES_LIST',
    GET_SCHEME_DETAOLS_BY_DOC_ENTRY:'GET_SCHEME_DETAOLS_BY_DOC_ENTRY',
    SET_SCHEME_DETAOLS_BY_DOC_ENTRY:'SET_SCHEME_DETAOLS_BY_DOC_ENTRY',
    SET_ACTIVE_SCHEMES_DATA:'SET_ACTIVE_SCHEMES_DATA',
    SET_SCEHEME_DETAILS_DATA:'SET_SCEHEME_DETAILS_DATA',
    GET_SAVE_SCHEME:"GET_SAVE_SCHEME",
    SAVE_THE_SCHEME:'SAVE_THE_SCHEME',
    HANDLE_ORDER:"HANDLE_ORDER",
    HANDLE_THE_PAYMENT:'HANDLE_THE_PAYMENT',
    UPDATE_THE_SCHEME:'UPDATE_THE_SCHEME',
    SET_DOC_AND_TOTAL:'SET_DOC_AND_TOTAL',
    GET_DOC_AND_TOTAL:'GET_DOC_AND_TOTAL',
    GET_MM_YY:'GET_MM_YY',
    GET_SCHEME_TYPE:'GET_SCHEME_TYPE',
    SET_MM_YY:'SET_MM_YY',
    SET_SCHEME_TYPE:'SET_SCHEME_TYPE',
    GET_CHIT_ITEM_GROUP:'GET_CHIT_ITEM_GROUP',
    SET_CHIT_ITEM_GROUP:'SET_CHIT_ITEM_GROUP'
}

export default actions;