const actions = {
   GET_SCHEME_DETAILS_BY_DOC_ENTRY:"GET_SCHEME_DETAILS_BY_DOC_ENTRY",
   SET_SCHEME_DETAILS_LIST_DATA:"SET_SCHEME_DETAILS_LIST_DATA",
   GET_SCHEME_GRAPH:'GET_SCHEME_GRAPH',
   SET_SCHEME_GRAPH:'SET_SCHEME_GRAPH'
}

export default actions