const actions = {
  LOGGED_IN: 'LOGGED_IN',
  GET_USER_DETAILS: "GET_USER_DETAILS",
  GET_FORGET_PASSWORD: 'GET_FORGET_PASSWORD',
  SET_FORGET_PASSWORD_DETAILS: 'SET_FORGET_PASSWORD_DETAILS',
  SET_LOGIN_INPUT_DETAILS: 'SET_LOGIN_INPUT_DETAILS',
  SET_USER_REGISTER_DETAILS:'SET_USER_REGISTER_DETAILS',
  USER_REGISRTATION:'USER_REGISRTATION',
  GET_LOGIN:'GET_LOGIN',
  SET_LOGIN:'SET_LOGIN',
  SET_LOG_DETAILS:"SET_LOG_DETAILS",
  SET_NEW_PASSWORD:'SET_NEW_PASSWORD',

  SET_USER_REGISTER:'SET_USER_REGISTER',
  SET_HANDLE_OTP:'SET_HANDLE_OTP',
  HANDLE_OTP:'HANDLE_OTP',
  HANDLE_VALID_PHONENUMBER:'HANDLE_VALID_PHONENUMBER',
  HANDLE_EXIST_VALID_PHONENUMBER:'HANDLE_EXIST_VALID_PHONENUMBER',
  DELETE_USER_ACCOUNT:'DELETE_USER_ACCOUNT',
}

export default actions;