const actions = {
   GET_GOLD_SILVER_RATES:'GET_GOLD_SILVER_RATES',
   SET_GOLD_SILVER_RATE:'SET_GOLD_SILVER_RATE',
   GET_SCHEMES_DATA:'GET_SCHEMES_DATA',
   SET_SCHEMES_DATA_LIST:'SET_SCHEMES_DATA_LIST',
   GET_SLIDER_LIST:"GET_SLIDER_LIST",
   SET_SLIDER_LIST_LOADING:"SET_SLIDER_LIST_LOADING",
   GET_SLIDER_LIST_LOADING:"GET_SLIDER_LIST_LOADING",
   SET_SLIDER_LIST:"SET_SLIDER_LIST",
   GET_OFFERS_LIST:'GET_OFFERS_LIST',
   SET_OFFERS_LIST:'SET_OFFERS_LIST',
   GET_NEW_ARRIVALS_LIST:'GET_NEW_ARRIVALS_LIST',
   SET_NEW_ARRIVALS_LIST:'SET_NEW_ARRIVALS_LIST',
   GET_LOCATION:"GET_LOCATION",
   SET_LOCATION:'SET_LOCATION',
   //added
   GET_INITIAL_HP_IMAGES:"GET_INITIAL_HP_IMAGES",
   GET_INITIAL_OF_IMAGES:"GET_INITIAL_OF_IMAGES",
   GET_INITIAL_NA_IMAGES:"GET_INITIAL_NA_IMAGES",
   SET_MYSCHEME_LOAD:'SET_MYSCHEME_LOAD'
}

export default actions;